Fiddling.

diff --git a/bin/rglexec b/bin/rglexec
--- a/bin/rglexec
+++ b/bin/rglexec
@@ -11,7 +11,6 @@ SCRIPT=$1
 
 # always make a little script out of it
 echo "#!/bin/bash"        > sc.$$
-echo "env |grep GLEXEC " >> sc.$$
 echo "$*"                >> sc.$$
 SCRIPT=sc.$$
 
@@ -23,12 +22,12 @@ scp -q $X509_USER_PROXY $TIER2_USER@${GATEWAY}:$REMOTE_TICKET 2> /dev/null
 scp -q $SCRIPT          $TIER2_USER@${GATEWAY}:/tmp/          2> /dev/null
 
 # Execute the script
-ssh $TIER2_USER@${GATEWAY} \
-  "export GLEXEC_CLIENT_CERT=$REMOTE_TICKET; export X509_USER_PROXY=$REMOTE_TICKET; /usr/sbin/glexec /tmp/$SCRIPT; echo \"RC: \$?\""
-# the RC is added so one could trap the return code for the internal command.
 
-# Cleanup remotely
-ssh $TIER2_USER@${GATEWAY} "rm /tmp/$SCRIPT $REMOTE_TICKET"
+cmd="export GLEXEC_CLIENT_CERT=$REMOTE_TICKET; export X509_USER_PROXY=$REMOTE_TICKET; "
+cmd="$cmd /usr/sbin/glexec /tmp/$SCRIPT; echo \"RC: \$?\"; rm -f /tmp/$SCRIPT $REMOTE_TICKET"
+
+ssh -x $TIER2_USER@${GATEWAY} $cmd
+# the RC is added so one could trap the return code for the internal command.
 
 # Cleanup locally
 if [ -e sc.$$ ]
