Small updates.

diff --git a/bin/rglexec b/bin/rglexec
--- a/bin/rglexec
+++ b/bin/rglexec
@@ -5,7 +5,8 @@
 #                                                                         v0.0 C.Paus (Aug 00, 2012)
 #===================================================================================================
 export X509_USER_PROXY=`voms-proxy-info -path`
-# T2TOOLS_SERVER=t2bat0210.cmsaf.mit.edu
+T2TOOLS_SERVER=t2bat0210.cmsaf.mit.edu
+#T2TOOLS_SERVER=t2srv0017.cmsaf.mit.edu
 REMOTE_TICKET=${X509_USER_PROXY}.$$
 SCRIPT=$1
 
@@ -18,6 +19,7 @@ SCRIPT=sc.$$
 chmod 755 $SCRIPT
 
 # Copy ticket and script
+#echo ECHO $T2TOOLS_SERVER
 scp -q $X509_USER_PROXY $T2TOOLS_USER@${T2TOOLS_SERVER}:$REMOTE_TICKET 2> /dev/null
 scp -q $SCRIPT          $T2TOOLS_USER@${T2TOOLS_SERVER}:/tmp/          2> /dev/null
 
@@ -26,13 +28,11 @@ scp -q $SCRIPT          $T2TOOLS_USER@${T2TOOLS_SERVER}:/tmp/          2> /dev/n
 cmd="export GLEXEC_CLIENT_CERT=$REMOTE_TICKET; export X509_USER_PROXY=$REMOTE_TICKET; "
 cmd="$cmd /usr/sbin/glexec /tmp/$SCRIPT; echo \"RC: \$?\"; rm -f /tmp/$SCRIPT $REMOTE_TICKET"
 
-ssh -x $T2TOOLS_USER@${T2TOOLS_SERVER} $cmd
-# careful the RC is added so one could trap the return code for the internal command.
+ssh -x $T2TOOLS_USER@${T2TOOLS_SERVER} $cmd | tee /tmp/rglexec.out.$$
+rc=`grep RC: /tmp/rglexec.out.$$ | cut -d' ' -f2`
+# careful the RC is added so we can trap the return code from the remote command and hand it over
 
 # Cleanup locally
-if [ -e sc.$$ ]
-then
-  rm sc.$$
-fi
+rm -f sc.$$ /tmp/rglexec.out.$$
 
-exit 0
+exit $rc
